import { parse, stringify } from 'yaml';
import type { RepositoryMap, RepositoryRelation } from './repository-map-types.js';
import { assertValidRepositoryMap, relationKey } from './repository-map-validation.js';

export function normalizeRepositoryRelation(relation: RepositoryRelation): RepositoryRelation {
  return {
    ...relation,
    evidence: [...relation.evidence].sort((left, right) =>
      [left.side, left.repository, left.path]
        .join('\u001f')
        .localeCompare([right.side, right.repository, right.path].join('\u001f')),
    ),
  };
}

export function normalizeRepositoryMap(map: RepositoryMap): RepositoryMap {
  return {
    schemaVersion: 1,
    repositories: [...map.repositories]
      .map((repository) => ({ ...repository }))
      .sort((left, right) => left.id.localeCompare(right.id)),
    relations: [...map.relations]
      .map(normalizeRepositoryRelation)
      .sort((left, right) => relationKey(left).localeCompare(relationKey(right))),
  };
}

export function parseRepositoryMap(content: string): RepositoryMap {
  const value: unknown = parse(content);
  assertValidRepositoryMap(value);
  return normalizeRepositoryMap(value);
}

export function serializeRepositoryMap(map: RepositoryMap): string {
  assertValidRepositoryMap(map);
  return `${stringify(normalizeRepositoryMap(map), { lineWidth: 100 }).trimEnd()}\n`;
}

export function renderRepositoryMap(map: RepositoryMap): string {
  assertValidRepositoryMap(map);
  const sorted = normalizeRepositoryMap(map);
  const lines = [
    '# Personal Repository Map',
    '',
    '<!-- generated from repository-map.yaml; do not edit this file directly -->',
    '',
    '这是跨仓决策索引，不是架构文档、运行时拓扑或调查报告。关系方向始终为 provider → contract → consumer。',
    '',
    '## Repositories',
    '',
  ];
  for (const repository of sorted.repositories) {
    lines.push(`### ${repository.id}`, '', repository.description, '');
    lines.push(`- Checkout: \`${repository.checkout}\``);
    lines.push(`- Owns: ${repository.owns.length > 0 ? repository.owns.join('；') : '—'}`);
    if (repository.aliases.length > 0) lines.push(`- Aliases: ${repository.aliases.join(', ')}`);
    if (repository.remotes.length > 0) lines.push(`- Remotes: ${repository.remotes.join(', ')}`);
    lines.push(`- Sources: ${repository.sources.map((path) => `\`${path}\``).join(', ')}`, '');
  }
  lines.push('## Direct relationships', '');
  for (const relation of sorted.relations) {
    lines.push(
      `### ${relation.type}: ${relation.provider} → \`${relation.contract}\` → ${relation.consumer}`,
      '',
    );
    for (const evidence of relation.evidence) {
      lines.push(`- ${evidence.side}: ${evidence.repository}/\`${evidence.path}\``);
    }
    lines.push('');
  }
  if (sorted.relations.length === 0) lines.push('_No verified direct relationships._', '');
  return `${lines.join('\n').trimEnd()}\n`;
}
