import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { onTestFinished, test } from 'vitest';
import { runCli } from '../cli.js';
import { initPersonal } from '../commands/init.js';
import { parseRepositoryMap, serializeRepositoryMap } from '../lib/repository-map.js';
import { capturedIo, harnessRuntime } from './helpers/harness.js';

function validMap() {
  return {
    schemaVersion: 1 as const,
    repositories: [
      {
        id: 'gateway',
        description: 'Routes public HTTP contracts to platform services.',
        checkout: 'platform/gateway',
        owns: ['public API routing'],
        aliases: ['api-gateway'],
        remotes: [],
        sources: ['README.md'],
      },
      {
        id: 'account',
        description: 'Owns account identity and session contracts.',
        checkout: 'platform/account',
        owns: ['identity'],
        aliases: [],
        remotes: [],
        sources: ['README.md'],
      },
    ],
    relations: [
      {
        type: 'http-api' as const,
        provider: 'account',
        contract: '/account/v1/session',
        consumer: 'gateway',
        evidence: [
          { repository: 'account', side: 'provider' as const, path: 'routes/session.ts' },
          { repository: 'gateway', side: 'consumer' as const, path: 'config/routes.yaml' },
        ],
      },
    ],
  };
}

function fixtureRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'harness-repository-map-cli-'));
  onTestFinished(() => rmSync(root, { recursive: true, force: true }));
  return root;
}

test('repository-map CLI initializes, checks, renders, verifies, maintains, and reconciles', () => {
  const root = fixtureRoot();
  const runtime = harnessRuntime(root, {
    harnessRoot: join(root, 'host', 'agent-harness'),
    installedHarness: join(root, 'installed', 'agent-harness'),
  });
  mkdirSync(runtime.harnessRoot, { recursive: true });
  writeFileSync(
    join(runtime.harnessRoot, 'manifest.json'),
    JSON.stringify({
      harnessVersion: 'test',
      schemaVersion: 3,
      memorySchemaVersion: 1,
      node: '>=24.12.0',
    }),
  );
  mkdirSync(join(runtime.harnessRoot, 'templates', 'personal', 'projects'), { recursive: true });
  writeFileSync(
    join(runtime.harnessRoot, 'templates', 'personal', 'projects', 'repository-map.yaml'),
    serializeRepositoryMap(validMap()),
  );
  writeFileSync(
    join(runtime.harnessRoot, 'templates', 'personal', 'projects', 'repository-map.md'),
    '# Personal Repository Map\n\n<!-- generated from repository-map.yaml; do not edit this file directly -->\n',
  );
  mkdirSync(join(runtime.harnessRoot, 'templates', 'personal'), { recursive: true });
  writeFileSync(join(runtime.harnessRoot, 'templates', 'personal', 'README.md'), '# Personal\n');
  writeFileSync(join(runtime.harnessRoot, 'templates', 'personal', 'AGENTS.md'), '# Rules\n');
  initPersonal(runtime, capturedIo());
  assert.equal(existsSync(join(runtime.personalHome, 'projects', 'repository-map.yaml')), true);

  const checked = capturedIo();
  assert.equal(runCli(['repository-map', 'check', '--json'], { runtime, io: checked }), 0);
  assert.equal(JSON.parse(checked.logs[0]).valid, true);

  const rendered = capturedIo();
  assert.equal(runCli(['repository-map', 'render', '--write'], { runtime, io: rendered }), 0);
  assert.match(
    readFileSync(join(runtime.personalHome, 'projects', 'repository-map.md'), 'utf8'),
    /generated from repository-map\.yaml/,
  );

  for (const repository of validMap().repositories) {
    const checkout = join(runtime.repositoryRoot, repository.checkout);
    mkdirSync(checkout, { recursive: true });
    writeFileSync(join(checkout, 'README.md'), repository.id);
  }
  mkdirSync(join(runtime.repositoryRoot, 'platform/account/routes'), { recursive: true });
  mkdirSync(join(runtime.repositoryRoot, 'platform/gateway/config'), { recursive: true });
  writeFileSync(join(runtime.repositoryRoot, 'platform/account/routes/session.ts'), 'provider');
  writeFileSync(join(runtime.repositoryRoot, 'platform/gateway/config/routes.yaml'), 'consumer');
  const verified = capturedIo();
  assert.equal(
    runCli(['repository-map', 'verify', '--record', '--json'], { runtime, io: verified }),
    0,
  );
  assert.equal(JSON.parse(verified.logs[0]).result, 'passed');
  assert.equal(
    existsSync(join(runtime.installedHarness, 'state', 'repository-map', 'verification.json')),
    true,
  );

  const maintained = capturedIo();
  assert.equal(runCli(['repository-map', 'maintain', '--json'], { runtime, io: maintained }), 0);
  assert.deepEqual(JSON.parse(maintained.logs[0]).stale, []);

  writeFileSync(
    join(runtime.repositoryRoot, 'platform/account/package.json'),
    JSON.stringify({ name: '@example/account-client', version: '1.0.0' }),
  );
  writeFileSync(
    join(runtime.repositoryRoot, 'platform/gateway/package.json'),
    JSON.stringify({ dependencies: { '@example/account-client': '^1.0.0' } }),
  );
  const discovered = capturedIo();
  assert.equal(
    runCli(['repository-map', 'discover', 'packages', '--apply', '--json'], {
      runtime,
      io: discovered,
    }),
    0,
  );
  assert.equal(JSON.parse(discovered.logs[0]).appliedRelations.length, 1);

  const observations = join(root, 'observations.json');
  writeFileSync(
    observations,
    JSON.stringify({
      version: 1,
      extractor: { id: 'external.agent', version: '1' },
      repositories: [],
      relations: [
        {
          discovery: 'heuristic',
          type: 'rpc',
          provider: 'account',
          contract: 'Account.GetSession',
          consumer: 'gateway',
          evidence: [
            { repository: 'account', side: 'provider', path: 'routes/session.ts' },
            { repository: 'gateway', side: 'consumer', path: 'config/routes.yaml' },
          ],
        },
      ],
    }),
  );
  const reconciled = capturedIo();
  assert.equal(
    runCli(['repository-map', 'reconcile', observations, '--apply', '--json'], {
      runtime,
      io: reconciled,
    }),
    0,
  );
  assert.equal(JSON.parse(reconciled.logs[0]).proposals.length, 1);
  assert.equal(
    parseRepositoryMap(
      readFileSync(join(runtime.personalHome, 'projects', 'repository-map.yaml'), 'utf8'),
    ).relations.length,
    2,
  );

  writeFileSync(join(runtime.personalHome, 'projects', 'repository-map.md'), '# legacy user map\n');
  assert.throws(
    () => runCli(['repository-map', 'render', '--write'], { runtime, io: capturedIo() }),
    /Refusing to overwrite a legacy or user-managed repository map view/,
  );
  rmSync(join(runtime.installedHarness, 'state'), { recursive: true, force: true });
  const migration = join(root, 'repository-map.migration.yaml');
  writeFileSync(
    migration,
    readFileSync(join(runtime.personalHome, 'projects', 'repository-map.yaml'), 'utf8'),
  );
  const migrated = capturedIo();
  assert.equal(
    runCli(['repository-map', 'migrate', migration, '--apply', '--json'], {
      runtime,
      io: migrated,
    }),
    0,
  );
  assert.equal(JSON.parse(migrated.logs[0]).ready, true);
  assert.equal(
    readFileSync(join(runtime.personalHome, 'projects', 'repository-map.legacy.md'), 'utf8'),
    '# legacy user map\n',
  );
  assert.match(
    readFileSync(join(runtime.personalHome, 'projects', 'repository-map.md'), 'utf8'),
    /generated from repository-map\.yaml/,
  );
  assert.equal(
    existsSync(join(runtime.installedHarness, 'state', 'repository-map', 'verification.json')),
    true,
  );
});
